"""
core/report.py — Audit report generation.

Generates exportable reports in JSON and Markdown formats.
All reports are stored in the reports/ directory.
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from core.models import AuditResult, BatchResult


REPORTS_DIR = Path(__file__).parent.parent / "reports"


def ensure_reports_dir() -> Path:
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    return REPORTS_DIR


# ---------------------------------------------------------------------------
# JSON export
# ---------------------------------------------------------------------------

def export_json(
    result:    AuditResult | BatchResult,
    path:      Optional[str] = None,
    auto_name: bool          = True,
) -> str:
    """
    Export an audit result to a JSON file.

    Args:
        result:    AuditResult or BatchResult
        path:      Explicit output path. If None and auto_name=True,
                   generates a timestamped filename in reports/
        auto_name: Generate timestamped filename if path is None

    Returns:
        Path string of the written file
    """
    ensure_reports_dir()

    if path is None and auto_name:
        ts    = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        kind  = "batch" if isinstance(result, BatchResult) else "audit"
        path  = str(REPORTS_DIR / f"{kind}_{ts}.json")

    data = result.to_dict()
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)

    return path


# ---------------------------------------------------------------------------
# Markdown report
# ---------------------------------------------------------------------------

def export_markdown(
    result:    AuditResult,
    path:      Optional[str] = None,
    auto_name: bool          = True,
) -> str:
    """
    Export an audit result as a structured Markdown report.

    Args:
        result:    AuditResult
        path:      Explicit output path
        auto_name: Generate timestamped filename if path is None

    Returns:
        Path string of the written file
    """
    ensure_reports_dir()

    if path is None and auto_name:
        ts   = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        path = str(REPORTS_DIR / f"audit_{ts}.md")

    md = _build_markdown(result)
    with open(path, "w", encoding="utf-8") as f:
        f.write(md)

    return path


def _build_markdown(r: AuditResult) -> str:
    """Build a Markdown report string from an AuditResult."""
    inp   = r.audit_input
    board = r.board
    cc    = r.crypto_chain
    ts    = r.timestamp

    status_icon = "✅" if r.fully_verified else "❌"

    lines = [
        "# BC.Game Mines Provably Fair Audit Report",
        "",
        f"> Generated by **bc-mines-lab-v1.0** · {ts}",
        "> This report is for educational and auditing purposes only.",
        "",
        "---",
        "",
        f"## {status_icon} Audit Status: {'VERIFIED' if r.fully_verified else 'ISSUES DETECTED'}",
        "",
    ]

    # Reference board warning
    if not r.reference_verified:
        lines += [
            "> ⚠️ **Warning:** The reference board array is partially unconfirmed.",
            "> The last 6 values have not been verified against the live BC.Game source.",
            "> Results may differ for rounds that depend on those shuffle positions.",
            "",
        ]

    # Input parameters
    lines += [
        "## Input Parameters",
        "",
        "| Parameter | Value |",
        "|-----------|-------|",
        f"| Label | {inp.label or '—'} |",
        f"| Server Seed | `{inp.server_seed}` |",
        f"| Server Seed Hash | `{inp.server_seed_hash or '—'}` |",
        f"| Client Seed | `{inp.client_seed}` |",
        f"| Nonce | `{inp.nonce}` |",
        f"| Mine Count | `{inp.mine_count}` |",
        "",
    ]

    # Commitment verification
    lines += ["## Commitment Verification", ""]
    if r.commitment:
        c    = r.commitment
        icon = "✅" if c.verified else "❌"
        lines += [
            f"**Result:** {icon} {'VERIFIED' if c.verified else 'FAILED'}",
            "",
            "| Field | Value |",
            "|-------|-------|",
            f"| Published Hash | `{c.published_hash}` |",
            f"| Computed Hash | `{c.computed_hash}` |",
            f"| Match | {'Yes ✅' if c.verified else 'No ❌'} |",
            "",
            f"_{c.match_detail}_",
            "",
        ]
    else:
        lines += ["_No server seed hash provided — commitment check skipped._", ""]

    # Cryptographic chain
    lines += [
        "## Cryptographic Derivation Chain",
        "",
        "| Step | Value |",
        "|------|-------|",
        f"| HMAC message | `{cc.hmac_input_message}` |",
        f"| HMAC-SHA256 result | `{cc.hmac_result}` |",
        f"| Pass 1 seed | `{cc.pass1_seed}` |",
        f"| SHA256(pass1_seed) | `{cc.pass1_seed_sha256}` |",
        f"| Pass 2 seed | `{cc.pass2_seed}` |",
        f"| SHA256(pass2_seed) | `{cc.pass2_seed_sha256}` |",
        "",
    ]

    # Shuffle passes
    lines += [
        "## Shuffle Passes",
        "",
        "### Pass 1",
        f"- Input array: `{r.pass1.input_array}`",
        f"- Output:      `{r.pass1.sorted_result}`",
        "",
        "### Pass 2",
        f"- Input array: `{r.pass2.input_array}`",
        f"- Output:      `{r.pass2.sorted_result}`",
        "",
    ]

    # Board
    lines += [
        "## Derived Board",
        "",
        f"**Mine count:** {board.mine_count}",
        f"**Mine positions (1-based):** `{sorted(board.mine_positions_1b)}`",
        f"**Mine positions (0-based):** `{sorted(board.mine_positions_0b)}`",
        "",
        "### Grid",
        "",
        "| C1 | C2 | C3 | C4 | C5 |",
        "|----|----|----|----|----|",
    ]

    grid = board.board_grid
    for row in grid:
        cells = []
        for i, cell_type in enumerate(row):
            if cell_type == "MINE":
                cells.append("💣")
            else:
                cells.append("💎")
        lines.append("| " + " | ".join(cells) + " |")

    lines += [
        "",
        "_💣 = Mine  💎 = Safe_",
        "",
    ]

    # Position comparison
    if r.claimed_mines is not None:
        icon  = "✅" if r.positions_match else "❌"
        lines += [
            "## Position Comparison",
            "",
            f"**Result:** {icon} {'MATCH' if r.positions_match else 'MISMATCH'}",
            "",
            f"| | Positions |",
            f"|--|-----------|",
            f"| Derived | `{sorted(board.mine_positions_1b)}` |",
            f"| Claimed | `{sorted(r.claimed_mines)}` |",
            "",
        ]

    # Reproducibility statement
    lines += [
        "## Reproducibility Statement",
        "",
        "This audit was performed using the exact BC.Game provably fair algorithm:",
        "",
        "1. `HMAC-SHA256(key=serverSeed, message=clientSeed:nonce)`",
        "2. `createNums(ALL_NUMS, hmac_result)` — hash rotation + descending sort",
        "3. `createNums(pass1_output, SHA256(hmac_result))` — second pass",
        "4. First `mineCount` values of final array = mine positions",
        "",
        "The reference array (`ALL_NUMS`) was observed from BC.Game's frontend",
        "provably fair documentation. See `data/reference_board.py` for details.",
        "",
        "---",
        "",
        "_Generated by bc-mines-lab-v1.0 — Educational use only._",
        "_No betting automation. No exploit claims. No account interaction._",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Batch Markdown summary
# ---------------------------------------------------------------------------

def export_batch_markdown(
    batch: BatchResult,
    path:  Optional[str] = None,
) -> str:
    """Export a batch result summary as Markdown."""
    ensure_reports_dir()

    if path is None:
        ts   = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        path = str(REPORTS_DIR / f"batch_{ts}.md")

    lines = [
        "# BC.Game Mines Batch Audit Report",
        "",
        f"> Generated: {batch.timestamp}",
        "",
        "## Summary",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total Rounds | {batch.total} |",
        f"| Passed | ✅ {batch.passed} |",
        f"| Failed | ❌ {batch.failed} |",
        f"| Errors | ⚠️ {batch.errors} |",
        f"| Pass Rate | {batch.pass_rate:.1%} |",
        "",
        "## Per-Round Results",
        "",
        "| # | Label | Mines | Positions | Commit | Match | Status |",
        "|---|-------|-------|-----------|--------|-------|--------|",
    ]

    for i, r in enumerate(batch.results, 1):
        label  = r.audit_input.label or f"round-{i}"
        mines  = ", ".join(str(p) for p in sorted(r.board.mine_positions_1b))
        commit = "✅" if (r.commitment and r.commitment.verified) else ("❌" if r.commitment else "—")
        match  = "✅" if r.positions_match is True else ("❌" if r.positions_match is False else "—")
        status = "✅ PASS" if r.fully_verified else "❌ FAIL"
        lines.append(f"| {i} | {label} | {r.audit_input.mine_count} | `{mines}` | {commit} | {match} | {status} |")

    lines += ["", "---", "_bc-mines-lab-v1.0 — Educational use only._"]

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return path
